name: Java CI

on: [push]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
      - name: Maven to Gradle
        run: echo no | gradle init --type pom --dsl groovy
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: add lombok
        run: sed -i "/dependencies {/a\annotationProcessor 'org.projectlombok:lombok:1.18.12'" build.gradle
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build --parallel -x test